lang: en
name: Julia Vallina · Frontend developer
title: Julia Vallina · Frontend developer
# see https://ogp.me/#types
type: website
url: https://juliavallina.com
image: https://avatars1.githubusercontent.com/u/3521323?s=460&u=8e41a8d7be49e37559693cf386cf940023fe38d0&v=4
description: Frontend nonsense and more 🏳️‍🌈💜 She/her.
